const KEY='football-empire-manager-save-v1';
let editId='';
const nums=['age','overall','potential','value','salary','fitness','morale','form','attack','defense','speed','stamina','technique','passing','shooting','goalkeeping'];
function readSave(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function cell(v){return String(v??'')}
function num(v){return Number(v||0)}
function esc(v){return cell(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')}
function input(k,p){return '<label>'+k+' <input id="'+k+'" value="'+esc(p[k])+'"></label> '}
function render(){const s=readSave();const el=document.getElementById('app');if(!s){el.textContent='No save game found';return}const players=s.players||[];let html='<p><b>Club:</b> '+esc(s.club?.name)+' | <b>Players:</b> '+players.length+' | <b>Market:</b> '+(s.transferMarket||[]).length+' | <b>Academy:</b> '+(s.academyProspects||[]).length+'</p>';if(editId){const p=players.find(x=>x.id===editId);if(p){html+='<h3>Edit player</h3><p>'+input('name',p)+' Position <select id="position"><option>GK</option><option>DF</option><option>MF</option><option>FW</option></select></p>';html+='<p>'+input('avatarUrl',p)+input('realWorldName',p)+' VIP <input id="isVip" type="checkbox" '+(p.isVip?'checked':'')+'></p><p>';nums.forEach(k=>html+=input(k,p));html+='</p><p><button onclick="saveEdit()">Save</button> <button onclick="cancelEdit()">Cancel</button></p>'}}html+='<table border="1" cellpadding="6"><tr><th>Name</th><th>Pos</th><th>Age</th><th>OVR</th><th>POT</th><th>Salary</th><th>VIP</th><th></th></tr>';players.forEach(p=>{html+='<tr><td>'+esc(p.name)+'</td><td>'+esc(p.position)+'</td><td>'+esc(p.age)+'</td><td>'+esc(p.overall)+'</td><td>'+esc(p.potential)+'</td><td>'+esc(p.salary)+'</td><td>'+(p.isVip?'VIP':'')+'</td><td><button onclick="editPlayer(\''+p.id+'\')">Edit</button></td></tr>'});html+='</table>';el.innerHTML=html;if(editId){const p=players.find(x=>x.id===editId);if(p)document.getElementById('position').value=p.position||'MF'}}
function editPlayer(id){editId=id;render()}
function cancelEdit(){editId='';render()}
function saveEdit(){const s=readSave();const p=(s.players||[]).find(x=>x.id===editId);if(!p)return;p.name=document.getElementById('name').value;p.position=document.getElementById('position').value;p.avatarUrl=document.getElementById('avatarUrl').value;p.realWorldName=document.getElementById('realWorldName').value;p.isVip=document.getElementById('isVip').checked;nums.forEach(k=>p[k]=num(document.getElementById(k).value));save(s);editId='';render()}
