const SAVE_KEY='football-empire-manager-save-v1';
let cachedSave=null;
function read(){try{return cachedSave||JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}}
function blockedMap(){const s=read();const map=new Map();(s?.players||[]).forEach(p=>{if(p.status==='injured')map.set(p.name,'INJ đến ngày '+(p.injuryUntilDay||'?'));if(p.status==='suspended')map.set(p.name,'SUS đến ngày '+(p.suspendedUntilDay||'?'))});return map}
function badge(text){const b=document.createElement('span');b.className='availability-badge';b.textContent=text;return b}
function warning(){const s=read();let box=document.querySelector('.lineup-warning-box');if(!s?.lineupWarning){if(box)box.remove();return}if(!box){box=document.createElement('div');box.className='lineup-warning-box';document.body.appendChild(box)}box.textContent=s.lineupWarning}
function resetMarks(){document.querySelectorAll('.availability-badge').forEach(x=>x.remove());document.querySelectorAll('.player-unavailable').forEach(x=>x.classList.remove('player-unavailable'));document.querySelectorAll('input[type="checkbox"][data-disabled-by-availability="1"]').forEach(cb=>{cb.disabled=false;cb.title='';delete cb.dataset.disabledByAvailability})}
function apply(){resetMarks();const map=blockedMap();document.querySelectorAll('tr').forEach(row=>{const txt=row.textContent||'';for(const [name,status] of map){if(!txt.includes(name))continue;row.classList.add('player-unavailable');const nameCell=row.querySelector('td:nth-child(2),td:first-child');if(nameCell&&!nameCell.querySelector('.availability-badge'))nameCell.appendChild(badge(status));const cb=row.querySelector('input[type="checkbox"]');if(cb){cb.disabled=true;cb.dataset.disabledByAvailability='1';cb.title='Cầu thủ đang chấn thương/treo giò';}}});document.querySelectorAll('.pitch-player,.player-card,.player-modal').forEach(el=>{const txt=el.textContent||'';for(const [name,status] of map){if(!txt.includes(name))continue;el.classList.add('player-unavailable');if(!el.querySelector('.availability-badge'))el.appendChild(badge(status));}});warning()}
const style=document.createElement('style');style.textContent='.player-unavailable{opacity:.58!important;filter:saturate(.65)}.availability-badge{display:inline-flex;margin-left:8px;padding:2px 7px;border-radius:999px;background:#ef4444;color:white;font-size:11px;font-weight:900;vertical-align:middle}.lineup-warning-box{position:fixed;left:50%;top:16px;transform:translateX(-50%);z-index:10000;max-width:min(680px,calc(100vw - 32px));padding:12px 16px;border-radius:16px;background:#991b1b;color:white;font-weight:800;box-shadow:0 18px 45px rgba(0,0,0,.28);text-align:center}';document.head.appendChild(style);
window.addEventListener('football-state-updated',e=>{cachedSave=e.detail;apply()});
setInterval(()=>{cachedSave=null;apply()},800);
