import type { AcademyProspect, Club, ClubNews, GameLog, GameState, LeagueTeam, MatchEvent, MatchResult, OpponentClub, Player, PlayerIntegrityIssue, PlayerOwnership, Position, Tactic, TransferMessage } from './types';

const firstNames = ['Minh', 'Bảo', 'Khang', 'Duy', 'Long', 'Nam', 'Quân', 'Huy', 'Phong', 'Đạt', 'Việt', 'Sơn', 'Tuấn', 'Hải', 'Khoa'];
const lastNames = ['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Phan', 'Vũ', 'Đặng', 'Bùi', 'Đỗ', 'Võ', 'Huỳnh'];
const botClubs = ['Sài Gòn Tigers', 'Hà Nội Dragons', 'Mekong United', 'Đà Nẵng Warriors', 'Huế Imperial', 'Nha Trang Waves', 'Cần Thơ Lions'];
const tactics: Tactic[] = ['balanced', 'attacking', 'defensive', 'counter', 'possession', 'pressing'];
const MAX_ACTIONS = 3;
const MARKET_LIMIT = 48;
const MIN_AI_SQUAD_SIZE = 18;
const MAX_AI_SQUAD_SIZE = 26;

const rand = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
const clamp = (value: number, min = 1, max = 99) => Math.max(min, Math.min(max, value));
const id = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const msg = (type: TransferMessage['type'], text: string): TransferMessage => ({ type, text });

function makeNews(state: GameState, type: ClubNews['type'], title: string, text: string): ClubNews { return { id: id(), day: state.day, season: state.season, type, title, text }; }
function pushNews(state: GameState, news: ClubNews): GameState { return { ...state, news: [news, ...(state.news ?? [])].slice(0, 30) }; }
function makeLog(state: GameState, actor: string, type: GameLog['type'], message: string, meta?: GameLog['meta']): GameLog { return { id: id(), day: state.day, season: state.season, actor, type, message, meta }; }
function makeAiLog(state: GameState, actor: string, action: string, message: string, meta?: GameLog['meta']): GameLog { return makeLog(state, actor, 'ai', message, { action, ...(meta ?? {}) }); }
function pushLog(state: GameState, log: GameLog): GameState { return { ...state, logs: [log, ...(state.logs ?? [])].slice(0, 250) }; }
function spendAction(state: GameState, cost = 1): GameState | null { return state.actionsRemaining >= cost ? { ...state, actionsRemaining: state.actionsRemaining - cost } : null; }
function positionForIndex(index: number): Position { if (index < 2) return 'GK'; if (index < 9) return 'DF'; if (index < 16) return 'MF'; return 'FW'; }
function averageOverall(players: Player[]) { if (!players.length) return 0; return Math.round(players.slice(0, 11).reduce((sum, p) => sum + p.overall, 0) / Math.min(players.length, 11)); }

export function buildPlayerOwnership(state: Pick<GameState, 'club' | 'players' | 'transferMarket' | 'academyProspects' | 'opponentSquads'>): Record<string, PlayerOwnership> {
  const registry: Record<string, PlayerOwnership> = {};
  const setOwner = (player: Player, owner: PlayerOwnership) => { if (!registry[player.id]) registry[player.id] = owner; };
  for (const player of state.players ?? []) setOwner(player, { playerId: player.id, ownerType: 'user', ownerName: state.club?.name ?? 'User Club', source: 'players' });
  for (const [teamName, squad] of Object.entries(state.opponentSquads ?? {})) for (const player of squad ?? []) setOwner(player, { playerId: player.id, ownerType: 'opponent', ownerName: teamName, source: 'opponentSquads' });
  for (const player of state.transferMarket ?? []) setOwner(player, { playerId: player.id, ownerType: 'market', ownerName: 'Transfer Market', source: 'transferMarket' });
  for (const player of state.academyProspects ?? []) setOwner(player, { playerId: player.id, ownerType: 'academy', ownerName: 'Academy', source: 'academyProspects' });
  return registry;
}

export function checkPlayerIntegrity(state: GameState): PlayerIntegrityIssue[] {
  const locations: Record<string, { player: Player; location: string; expectedOwner: PlayerOwnership }[]> = {};
  const add = (player: Player, location: string, expectedOwner: PlayerOwnership) => { locations[player.id] = [...(locations[player.id] ?? []), { player, location, expectedOwner }]; };
  for (const player of state.players ?? []) add(player, `Đội mình: ${state.club?.name ?? 'User Club'}`, { playerId: player.id, ownerType: 'user', ownerName: state.club?.name ?? 'User Club', source: 'players' });
  for (const [teamName, squad] of Object.entries(state.opponentSquads ?? {})) for (const player of squad ?? []) add(player, `Đội AI: ${teamName}`, { playerId: player.id, ownerType: 'opponent', ownerName: teamName, source: 'opponentSquads' });
  for (const player of state.transferMarket ?? []) add(player, 'Transfer Market', { playerId: player.id, ownerType: 'market', ownerName: 'Transfer Market', source: 'transferMarket' });
  for (const player of state.academyProspects ?? []) add(player, 'Academy', { playerId: player.id, ownerType: 'academy', ownerName: 'Academy', source: 'academyProspects' });
  const issues: PlayerIntegrityIssue[] = [];
  for (const [playerId, entries] of Object.entries(locations)) {
    const player = entries[0]?.player;
    const registryOwner = state.playerOwnership?.[playerId];
    if (!player) continue;
    if (entries.length > 1) issues.push({ id: `${playerId}-duplicate`, severity: 'error', playerId, playerName: player.name, type: 'duplicate', message: `${player.name} đang xuất hiện ở ${entries.length} nơi.`, locations: entries.map(e => e.location) });
    if (!registryOwner) issues.push({ id: `${playerId}-missing-owner`, severity: 'warning', playerId, playerName: player.name, type: 'missing_owner', message: `${player.name} chưa có owner trong registry.`, locations: entries.map(e => e.location) });
    else {
      const expected = entries[0].expectedOwner;
      if (registryOwner.ownerType !== expected.ownerType || registryOwner.ownerName !== expected.ownerName || registryOwner.source !== expected.source) issues.push({ id: `${playerId}-owner-mismatch`, severity: 'warning', playerId, playerName: player.name, type: 'owner_mismatch', message: `${player.name} có owner không khớp registry.`, locations: [`Expected: ${expected.ownerType}/${expected.ownerName}/${expected.source}`, `Actual: ${registryOwner.ownerType}/${registryOwner.ownerName}/${registryOwner.source}`] });
    }
  }
  for (const [playerId, owner] of Object.entries(state.playerOwnership ?? {})) {
    if (!locations[playerId]) issues.push({ id: `${playerId}-orphan-registry`, severity: 'warning', playerId, playerName: playerId, type: 'orphan_registry', message: `Registry có owner cho cầu thủ không còn nằm trong danh sách nào.`, locations: [`${owner.ownerType}/${owner.ownerName}/${owner.source}`] });
  }
  return issues;
}

export function syncPlayerOwnership(state: GameState): GameState {
  const withOwnership = { ...state, playerOwnership: buildPlayerOwnership(state) };
  const ownershipIssues = checkPlayerIntegrity(withOwnership);
  let next: GameState = { ...withOwnership, ownershipIssues };
  const existingIssueIds = new Set((state.logs ?? []).map(log => typeof log.meta?.issueId === 'string' ? log.meta.issueId : '').filter(Boolean));
  for (const issue of ownershipIssues.filter(issue => !existingIssueIds.has(issue.id)).slice(0, 8)) next = pushLog(next, makeLog(next, 'Integrity Check', 'system', `Ownership ${issue.severity}: ${issue.message}`, { issueId: issue.id, issueType: issue.type, playerId: issue.playerId, player: issue.playerName, locations: issue.locations.join(' | ') }));
  return next;
}

function generatePlayer(index: number, qualityOffset = 0, forcedAge?: number): Player {
  const position = positionForIndex(index % 22);
  const age = forcedAge ?? rand(17, 33);
  const base = rand(48, 72) + qualityOffset;
  const potential = clamp(base + rand(3, age < 22 ? 25 : 10));
  const boost = (target: Position) => position === target ? rand(8, 18) : rand(-3, 6);
  const attack = clamp(base + boost('FW'));
  const defense = clamp(base + boost('DF'));
  const goalkeeping = position === 'GK' ? clamp(base + rand(12, 22)) : rand(5, 25);
  const shooting = clamp(base + boost('FW'));
  const passing = clamp(base + boost('MF'));
  const technique = clamp(base + rand(-5, 12));
  const speed = clamp(base + rand(-8, 12));
  const stamina = clamp(base + rand(-5, 12));
  const overall = position === 'GK' ? Math.round(goalkeeping * 0.65 + defense * 0.15 + passing * 0.1 + stamina * 0.1) : Math.round((attack + defense + speed + stamina + technique + passing + shooting) / 7);
  return { id: id(), name: `${lastNames[rand(0, lastNames.length - 1)]} ${firstNames[rand(0, firstNames.length - 1)]}`, age, position, overall, potential, value: overall * overall * 120, salary: overall * 75, fitness: rand(82, 100), morale: rand(55, 90), form: rand(45, 85), attack, defense, speed, stamina, technique, passing, shooting, goalkeeping };
}

export function generatePlayers(): Player[] { return Array.from({ length: 22 }, (_, i) => generatePlayer(i)).sort((a, b) => b.overall - a.overall); }
export function generateTransferMarket(count = 20): Player[] { return Array.from({ length: count }, (_, i) => generatePlayer(i, rand(-4, 8))).map(p => ({ ...p, value: Math.round(p.value * 1.25), salary: Math.round(p.salary * 1.15) })).sort((a, b) => b.overall - a.overall); }
function generateFreeAgents(count = 3): Player[] { return generateTransferMarket(count).map(p => ({ ...p, value: Math.round(p.value * 0.95), salary: Math.round(p.salary * 0.95) })); }
function mergeMarket(existing: Player[], incoming: Player[], limit = MARKET_LIMIT): Player[] {
  const seen = new Set<string>();
  return [...incoming, ...existing].filter(player => {
    if (seen.has(player.id)) return false;
    seen.add(player.id);
    return true;
  }).sort((a, b) => b.overall - a.overall || a.value - b.value).slice(0, limit);
}
export function generateAcademyProspects(count = 3): AcademyProspect[] { return Array.from({ length: count }, (_, i) => { const roll = rand(1, 100); const rarity: AcademyProspect['rarity'] = roll >= 92 ? 'Wonderkid' : roll >= 65 ? 'Triển vọng' : 'Thường'; const offset = rarity === 'Wonderkid' ? -4 : rarity === 'Triển vọng' ? -9 : -14; const p = generatePlayer(i + rand(0, 21), offset, rand(16, 19)); const potentialBoost = rarity === 'Wonderkid' ? rand(22, 34) : rarity === 'Triển vọng' ? rand(13, 24) : rand(5, 15); const prospect = { ...p, potential: clamp(p.overall + potentialBoost, 1, 99) }; return { ...prospect, signingFee: Math.round(prospect.value * (rarity === 'Wonderkid' ? 0.9 : 0.55)), rarity }; }).sort((a, b) => b.potential - a.potential); }
function generateOpponentSquads(teamNames: string[]): Record<string, Player[]> { return Object.fromEntries(teamNames.map((name, idx) => [name, Array.from({ length: 22 }, (_, i) => generatePlayer(i, rand(-6, 10) + Math.floor(idx / 2))).sort((a, b) => b.overall - a.overall)])); }
function generateOpponentClubs(teamNames: string[]): Record<string, OpponentClub> { return Object.fromEntries(teamNames.map((name, idx) => [name, { name, budget: 2_500_000 + idx * 350_000 + rand(0, 850_000), reputation: 20 + idx * 4, tactic: tactics[rand(0, tactics.length - 1)] }])); }
export function buildDefaultLineup(players: Player[]): string[] { const pick = (pos: Position, count: number) => players.filter(p => p.position === pos).slice(0, count).map(p => p.id); return [...pick('GK', 1), ...pick('DF', 4), ...pick('MF', 4), ...pick('FW', 2)]; }
export function createLeague(userClubName: string): LeagueTeam[] { return [userClubName, ...botClubs].map((name, index) => ({ id: id(), name, power: index === 0 ? 62 : rand(54, 74), played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, points: 0 })); }
export function createFixtures(userClubName: string, names: string[]): MatchResult[] { const opponents = names.filter(n => n !== userClubName); return opponents.flatMap((opponent, index) => ([{ id: id(), round: index + 1, day: 3 + index * 4, home: userClubName, away: opponent, homeScore: 0, awayScore: 0, events: [], played: false }, { id: id(), round: index + 8, day: 31 + index * 4, home: opponent, away: userClubName, homeScore: 0, awayScore: 0, events: [], played: false }])).sort((a, b) => a.day - b.day); }

export function createNewGame(clubName: string, stadium: string): GameState {
  const players = generatePlayers();
  const club: Club = { id: id(), name: clubName.trim() || 'PMEDIA FC', stadium: stadium.trim() || 'Empire Arena', budget: 5_000_000, reputation: 25, fans: 8_000, tactic: 'balanced', lineup: buildDefaultLineup(players) };
  const league = createLeague(club.name);
  const opponentNames = league.map(t => t.name).filter(name => name !== club.name);
  const state: GameState = { club, players, transferMarket: generateFreeAgents(12), academyProspects: [], news: [], logs: [], opponentClubs: generateOpponentClubs(opponentNames), opponentSquads: generateOpponentSquads(opponentNames), playerOwnership: {}, ownershipIssues: [], league, fixtures: createFixtures(club.name, league.map(t => t.name)), currentRound: 1, season: 1, day: 1, actionsRemaining: MAX_ACTIONS, maxActionsPerDay: MAX_ACTIONS, lastMatch: null, transferMessage: null, lastSeasonSummary: null };
  const initialized = syncPlayerOwnership(state);
  return pushLog(pushNews(initialized, makeNews(initialized, 'neutral', 'Mùa giải bắt đầu', `${club.name} chính thức bước vào mùa giải đầu tiên.`)), makeLog(initialized, 'System', 'system', 'Khởi tạo career mới.'));
}
function tacticBonus(tactic: Tactic) { return { balanced: { attack: 0, defense: 0 }, attacking: { attack: 8, defense: -5 }, defensive: { attack: -5, defense: 8 }, counter: { attack: 4, defense: 4 }, possession: { attack: 3, defense: 2 }, pressing: { attack: 6, defense: -2 } }[tactic]; }
function teamRating(players: Player[], lineup: string[], tactic: Tactic) { const active = lineup.map(pid => players.find(p => p.id === pid)).filter(Boolean) as Player[]; const selected = active.length ? active : players.slice(0, 11); const bonus = tacticBonus(tactic); const avg = (fn: (p: Player) => number) => selected.reduce((sum, p) => sum + fn(p), 0) / selected.length; return { attack: avg(p => p.position === 'GK' ? p.passing : (p.attack + p.shooting + p.passing + p.technique) / 4) + bonus.attack, defense: avg(p => p.position === 'GK' ? p.goalkeeping : (p.defense + p.stamina + p.speed) / 3) + bonus.defense, overall: avg(p => p.overall) + avg(p => (p.fitness + p.morale + p.form - 180) / 12) }; }
function goalsFor(attack: number, defense: number, homeBonus: number) { let goals = 0; const edge = attack - defense + homeBonus; for (let i = 0; i < 5 + rand(0, 3); i++) if (rand(1, 100) + edge > 72) goals++; return Math.min(5, goals); }
function addStanding(team: LeagueTeam, gf: number, ga: number) { team.played++; team.goalsFor += gf; team.goalsAgainst += ga; if (gf > ga) { team.won++; team.points += 3; } else if (gf === ga) { team.drawn++; team.points += 1; } else team.lost++; }
function buildEvents(home: string, away: string, homeScore: number, awayScore: number): MatchEvent[] { const events: MatchEvent[] = [{ minute: 1, type: 'info', text: `Trận đấu bắt đầu: ${home} vs ${away}.` }]; for (let i = 0; i < homeScore; i++) events.push({ minute: rand(8, 88), type: 'goal', text: `${home} ghi bàn! Khán đài nổ tung.` }); for (let i = 0; i < awayScore; i++) events.push({ minute: rand(8, 88), type: 'goal', text: `${away} ghi bàn sau một pha tấn công sắc nét.` }); if (Math.random() > 0.55) events.push({ minute: rand(20, 80), type: 'save', text: 'Thủ môn có pha cứu thua quan trọng.' }); if (Math.random() > 0.72) events.push({ minute: rand(55, 90), type: 'injury', text: 'Một cầu thủ bị đau nhẹ và cần theo dõi sau trận.' }); events.push({ minute: 90, type: 'info', text: `Kết thúc trận đấu: ${home} ${homeScore}-${awayScore} ${away}.` }); return events.sort((a, b) => a.minute - b.minute); }

function runOpponentAI(state: GameState): GameState {
  let next: GameState = { ...state, opponentClubs: { ...(state.opponentClubs ?? {}) }, opponentSquads: { ...(state.opponentSquads ?? {}) }, transferMarket: [...(state.transferMarket ?? [])] };
  for (const team of Object.values(next.opponentClubs)) {
    const squad = [...(next.opponentSquads[team.name] ?? [])];
    if (!squad.length) continue;
    const strength = averageOverall(squad);
    const avgFitness = Math.round(squad.slice(0, 11).reduce((sum, p) => sum + p.fitness, 0) / 11);
    const roll = rand(1, 100);
    if (avgFitness < 72 || roll <= 35) { const trained = squad.map(p => ({ ...p, fitness: clamp(p.fitness + rand(3, 8)), morale: clamp(p.morale + rand(0, 3)), overall: clamp(p.overall + (p.age <= 22 && p.overall < p.potential && Math.random() > 0.85 ? 1 : 0)) })).sort((a, b) => b.overall - a.overall); next.opponentSquads[team.name] = trained; next = pushLog(next, makeAiLog(next, team.name, 'training', `AI huấn luyện đội hình. Sức mạnh ${strength} → ${averageOverall(trained)}.`, { strengthBefore: strength, strengthAfter: averageOverall(trained), avgFitness })); continue; }
    if (roll <= 55 && squad.length > MIN_AI_SQUAD_SIZE) { const oldPlayer = squad.find(p => p.age >= 31) ?? squad[squad.length - 1]; const saleValue = Math.round(oldPlayer.value * 0.8); next.opponentSquads[team.name] = squad.filter(p => p.id !== oldPlayer.id); next.transferMarket = mergeMarket(next.transferMarket, [{ ...oldPlayer, value: Math.round(oldPlayer.value * 1.1) }]); next.opponentClubs[team.name] = { ...team, budget: team.budget + saleValue }; next = syncPlayerOwnership(pushLog(next, makeAiLog(next, team.name, 'sell', `AI bán ${oldPlayer.name}, thu ${saleValue.toLocaleString('vi-VN')} VND.`, { player: oldPlayer.name, value: saleValue, budgetAfter: team.budget + saleValue, playerId: oldPlayer.id, squadAfter: squad.length - 1 }))); continue; }
    if (roll <= 78 && team.budget > 650_000 && next.transferMarket.length && squad.length < MAX_AI_SQUAD_SIZE) { const affordable = next.transferMarket.filter(p => p.value <= team.budget && p.overall >= Math.max(58, strength - 4)).sort((a, b) => b.overall - a.overall); const target = affordable[0]; if (target) { next.opponentSquads[team.name] = [...squad, target].sort((a, b) => b.overall - a.overall); next.transferMarket = next.transferMarket.filter(p => p.id !== target.id); next.opponentClubs[team.name] = { ...team, budget: team.budget - target.value }; next = syncPlayerOwnership(pushLog(next, makeAiLog(next, team.name, 'buy', `AI mua ${target.name} với giá ${target.value.toLocaleString('vi-VN')} VND.`, { player: target.name, value: target.value, budgetAfter: team.budget - target.value, playerId: target.id, squadAfter: squad.length + 1 }))); continue; } }
    const tactic = strength < 63 ? 'defensive' : avgFitness > 84 ? 'pressing' : tactics[rand(0, tactics.length - 1)]; next.opponentClubs[team.name] = { ...team, tactic }; next = pushLog(next, makeAiLog(next, team.name, 'tactic', `AI điều chỉnh chiến thuật sang ${tactic}.`, { tactic, strength, avgFitness, squadSize: squad.length }));
  }
  return syncPlayerOwnership(next);
}

function randomDailyEvent(state: GameState): GameState { if (!state.club || Math.random() > 0.42) return state; const roll = rand(1, 100); if (roll <= 24) { const bonus = rand(60_000, 180_000); const next = { ...state, club: { ...state.club, budget: state.club.budget + bonus } }; return pushNews(pushLog(next, makeLog(next, state.club.name, 'finance', `Nhà tài trợ thưởng ${bonus.toLocaleString('vi-VN')} VND.`)), makeNews(next, 'good', 'Nhà tài trợ thưởng nóng', `Nhà tài trợ địa phương hỗ trợ thêm ${bonus.toLocaleString('vi-VN')} VND cho CLB.`)); } if (roll <= 45) { const player = state.players[rand(0, Math.min(state.players.length - 1, 10))]; const players = state.players.map(p => p.id === player.id ? { ...p, morale: clamp(p.morale + rand(5, 10)), form: clamp(p.form + rand(3, 8)) } : p); const next = syncPlayerOwnership({ ...state, players }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'training', `${player.name} tập tốt, tăng morale/form.`, { playerId: player.id, player: player.name })), makeNews(next, 'good', `${player.name} gây ấn tượng`, `${player.name} có buổi tập rất tốt, tinh thần và phong độ được cải thiện.`)); } if (roll <= 62) { const player = state.players[rand(0, Math.min(state.players.length - 1, 10))]; const players = state.players.map(p => p.id === player.id ? { ...p, fitness: clamp(p.fitness - rand(8, 16), 30, 100), morale: clamp(p.morale - rand(1, 4)) } : p); const next = syncPlayerOwnership({ ...state, players }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'training', `${player.name} bị đau nhẹ, giảm thể lực.`, { playerId: player.id, player: player.name })), makeNews(next, 'bad', `${player.name} bị đau nhẹ`, `${player.name} bị đau trong buổi tập và giảm thể lực.`)); } if (roll <= 78) { const fans = rand(120, 420); const next = { ...state, club: { ...state.club, fans: state.club.fans + fans } }; return pushNews(pushLog(next, makeLog(next, state.club.name, 'finance', `Tăng ${fans.toLocaleString('vi-VN')} fan mới.`)), makeNews(next, 'good', 'Fan hào hứng trước mùa giải', `CLB có thêm ${fans.toLocaleString('vi-VN')} người hâm mộ mới.`)); } if (roll <= 90) { const added = generateFreeAgents(rand(1, 3)); const next = syncPlayerOwnership({ ...state, transferMarket: mergeMarket(state.transferMarket ?? [], added) }); return pushNews(pushLog(next, makeLog(next, 'System', 'transfer', `Thị trường bổ sung ${added.length} free agent mới.`, { added: added.length })), makeNews(next, 'market', 'Free agents xuất hiện', `${added.length} cầu thủ tự do mới đã xuất hiện trên thị trường.`)); } const next = syncPlayerOwnership({ ...state, academyProspects: generateAcademyProspects() }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'training', 'Scout tự phát hiện nhóm cầu thủ trẻ.')), makeNews(next, 'academy', 'Scout báo tin tài năng trẻ', 'Bộ phận scout phát hiện một nhóm cầu thủ trẻ đáng chú ý.')); }
export function getTodayMatch(state: GameState) { return state.fixtures.find(f => !f.played && f.day === state.day) || null; }
export function advanceDay(state: GameState): GameState { if (isSeasonFinished(state)) return state; const players = state.players.map(p => ({ ...p, fitness: clamp(p.fitness + rand(4, 9)), morale: clamp(p.morale + rand(-1, 2)) })); const base = syncPlayerOwnership({ ...state, day: state.day + 1, actionsRemaining: state.maxActionsPerDay, players, transferMessage: msg('info', `Đã sang ngày ${state.day + 1}. Hành động đã được làm mới.`) }); return syncPlayerOwnership(randomDailyEvent(runOpponentAI(base))); }
export function simulateNextRound(state: GameState): GameState { const club = state.club; if (!club) return state; const match = getTodayMatch(state); if (!match) return { ...state, transferMessage: msg('error', 'Hôm nay không có trận đấu. Hãy dùng ngày trống để huấn luyện, scout hoặc chuyển nhượng.') }; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const userRating = teamRating(actionState.players, club.lineup, club.tactic); const opponent = actionState.league.find(t => t.name === (match.home === club.name ? match.away : match.home)); const opponentPower = opponent?.power ?? 60; const userIsHome = match.home === club.name; const userGoals = goalsFor(userRating.attack + userRating.overall * 0.2, opponentPower, userIsHome ? 5 : 0); const oppGoals = goalsFor(opponentPower, userRating.defense + userRating.overall * 0.15, userIsHome ? 0 : 5); const homeScore = userIsHome ? userGoals : oppGoals; const awayScore = userIsHome ? oppGoals : userGoals; const fixtures = actionState.fixtures.map(f => f.id === match.id ? { ...f, homeScore, awayScore, events: buildEvents(match.home, match.away, homeScore, awayScore), played: true } : f); const league = actionState.league.map(t => ({ ...t })); const homeTeam = league.find(t => t.name === match.home); const awayTeam = league.find(t => t.name === match.away); if (homeTeam && awayTeam) { addStanding(homeTeam, homeScore, awayScore); addStanding(awayTeam, awayScore, homeScore); } const sortedLeague = league.sort((a, b) => b.points - a.points || (b.goalsFor - b.goalsAgainst) - (a.goalsFor - a.goalsAgainst) || b.goalsFor - a.goalsFor); const players = actionState.players.map(p => ({ ...p, fitness: clamp(p.fitness - rand(2, 8), 30, 100), form: clamp(p.form + (userGoals >= oppGoals ? rand(0, 4) : rand(-4, 1))) })); const prize = userGoals > oppGoals ? 180_000 : userGoals === oppGoals ? 75_000 : 20_000; const resultState = syncPlayerOwnership({ ...actionState, club: { ...club, budget: club.budget + prize, fans: club.fans + (userGoals > oppGoals ? 350 : userGoals === oppGoals ? 80 : -120) }, players, league: sortedLeague, fixtures, currentRound: actionState.currentRound + 1, lastMatch: fixtures.find(f => f.id === match.id) || null, transferMessage: msg('success', 'Trận đấu hôm nay đã kết thúc.') }); const logged = pushLog(resultState, makeLog(resultState, club.name, 'match', `Đá trận ${match.home} ${homeScore}-${awayScore} ${match.away}.`)); return pushNews(logged, makeNews(logged, userGoals > oppGoals ? 'good' : userGoals === oppGoals ? 'neutral' : 'bad', `Kết quả: ${match.home} ${homeScore}-${awayScore} ${match.away}`, userGoals > oppGoals ? 'Đội bóng có thêm tiền thưởng và fan mới.' : userGoals === oppGoals ? 'Một trận hòa giúp đội bóng có thêm chút tiền thưởng.' : 'Kết quả không như mong muốn, một số fan đã rời đi.')); }
export function setTactic(state: GameState, tactic: Tactic): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const next = { ...actionState, club: { ...state.club, tactic }, transferMessage: msg('info', 'Đã thay đổi chiến thuật. Mất 1 lượt hành động.') }; return pushLog(next, makeLog(next, state.club.name, 'tactic', `Đổi chiến thuật sang ${tactic}.`)); }
export function setLineup(state: GameState, playerId: string): GameState { if (!state.club) return state; const exists = state.club.lineup.includes(playerId); const lineup = exists ? state.club.lineup.filter(id => id !== playerId) : state.club.lineup.length < 11 ? [...state.club.lineup, playerId] : state.club.lineup; return { ...state, club: { ...state.club, lineup } }; }
export function trainTeam(state: GameState): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; if (actionState.club!.budget < 50_000) return { ...state, transferMessage: msg('error', 'Không đủ ngân sách để huấn luyện.') }; const players = actionState.players.map(p => ({ ...p, overall: clamp(p.overall + (p.age <= 23 && p.overall < p.potential && Math.random() > 0.72 ? 2 : 0)), fitness: clamp(p.fitness + rand(4, 10)), morale: clamp(p.morale + rand(1, 5)) })).sort((a, b) => b.overall - a.overall); const next = syncPlayerOwnership({ ...actionState, players, club: { ...actionState.club!, budget: actionState.club!.budget - 50_000 }, transferMessage: msg('success', 'Đội bóng đã hoàn tất buổi huấn luyện hôm nay.') }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'training', 'Huấn luyện đội hình, trừ 50.000 VND.')), makeNews(next, 'neutral', 'Buổi huấn luyện hoàn tất', 'Toàn đội vừa hoàn tất buổi huấn luyện trong ngày.')); }
export function buyPlayer(state: GameState, playerId: string): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const player = actionState.transferMarket?.find(p => p.id === playerId); if (!player) return { ...state, transferMessage: msg('error', 'Không tìm thấy cầu thủ trên thị trường.') }; if (actionState.club!.budget < player.value) return { ...state, transferMessage: msg('error', `Ngân sách không đủ để mua ${player.name}.`) }; const next = syncPlayerOwnership({ ...actionState, club: { ...actionState.club!, budget: actionState.club!.budget - player.value }, players: [...actionState.players, player].sort((a, b) => b.overall - a.overall), transferMarket: actionState.transferMarket.filter(p => p.id !== playerId), transferMessage: msg('success', `Đã chiêu mộ ${player.name}.`) }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'transfer', `Mua ${player.name} với giá ${player.value.toLocaleString('vi-VN')} VND.`, { player: player.name, value: player.value, playerId: player.id })), makeNews(next, 'market', 'Tân binh cập bến', `${player.name} đã gia nhập CLB với giá ${player.value.toLocaleString('vi-VN')} VND.`)); }
export function sellPlayer(state: GameState, playerId: string): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; if (actionState.players.length <= 16) return { ...state, transferMessage: msg('error', 'Đội hình còn quá mỏng, không thể bán thêm cầu thủ.') }; const player = actionState.players.find(p => p.id === playerId); if (!player) return { ...state, transferMessage: msg('error', 'Không tìm thấy cầu thủ trong đội.') }; const saleValue = Math.round(player.value * 0.85); const next = syncPlayerOwnership({ ...actionState, club: { ...actionState.club!, budget: actionState.club!.budget + saleValue, lineup: actionState.club!.lineup.filter(id => id !== playerId) }, players: actionState.players.filter(p => p.id !== playerId), transferMarket: mergeMarket(actionState.transferMarket ?? [], [{ ...player, value: Math.round(player.value * 1.15) }]), transferMessage: msg('success', `Đã bán ${player.name} và thu về ${saleValue.toLocaleString('vi-VN')} VND.`) }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'transfer', `Bán ${player.name}, thu ${saleValue.toLocaleString('vi-VN')} VND.`, { player: player.name, value: saleValue, playerId: player.id })), makeNews(next, 'market', 'Cầu thủ rời CLB', `${player.name} đã rời đội bóng. CLB thu về ${saleValue.toLocaleString('vi-VN')} VND.`)); }
export function refreshTransferMarket(state: GameState): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const cost = 120_000; if (actionState.club!.budget < cost) return { ...state, transferMessage: msg('error', 'Không đủ ngân sách để làm mới thị trường.') }; const added = generateFreeAgents(rand(2, 4)); const next = syncPlayerOwnership({ ...actionState, club: { ...actionState.club!, budget: actionState.club!.budget - cost }, transferMarket: mergeMarket(actionState.transferMarket ?? [], added), transferMessage: msg('info', `Đã bổ sung ${added.length} free agent vào thị trường.`) }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'transfer', `Scout thị trường và bổ sung ${added.length} free agent, trừ ${cost.toLocaleString('vi-VN')} VND.`, { added: added.length, cost })), makeNews(next, 'market', 'Bổ sung free agents', `${added.length} cầu thủ tự do mới đã được thêm vào thị trường.`)); }
export function scoutAcademy(state: GameState): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const cost = 180_000; if (actionState.club!.budget < cost) return { ...state, transferMessage: msg('error', 'Không đủ ngân sách để scout tài năng trẻ.') }; const prospects = generateAcademyProspects(); const hasWonderkid = prospects.some(p => p.rarity === 'Wonderkid'); const next = syncPlayerOwnership({ ...actionState, club: { ...actionState.club!, budget: actionState.club!.budget - cost }, academyProspects: prospects, transferMessage: msg('success', 'Bộ phận scout đã gửi về 3 tài năng trẻ mới.') }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'training', 'Scout học viện, trừ 180.000 VND.')), makeNews(next, 'academy', hasWonderkid ? 'Phát hiện Wonderkid!' : 'Scout gửi báo cáo học viện', hasWonderkid ? 'Một tài năng trẻ hiếm đã xuất hiện trong báo cáo scout.' : 'Bộ phận scout đã gửi danh sách 3 cầu thủ trẻ mới.')); }
export function signAcademyProspect(state: GameState, playerId: string): GameState { if (!state.club) return state; const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const prospect = actionState.academyProspects.find(p => p.id === playerId); if (!prospect) return { ...state, transferMessage: msg('error', 'Không tìm thấy cầu thủ trẻ này.') }; if (actionState.club!.budget < prospect.signingFee) return { ...state, transferMessage: msg('error', `Không đủ ngân sách để ký ${prospect.name}.`) }; const { signingFee, rarity, ...player } = prospect; const next = syncPlayerOwnership({ ...actionState, club: { ...actionState.club!, budget: actionState.club!.budget - signingFee }, players: [...actionState.players, player].sort((a, b) => b.overall - a.overall), academyProspects: actionState.academyProspects.filter(p => p.id !== playerId), transferMessage: msg('success', `Đã ký hợp đồng với ${player.name} (${rarity}).`) }); return pushNews(pushLog(next, makeLog(next, state.club.name, 'transfer', `Ký cầu thủ học viện ${player.name} (${rarity}).`, { playerId: player.id, player: player.name })), makeNews(next, 'academy', 'Cầu thủ trẻ ký hợp đồng', `${player.name} (${rarity}) đã gia nhập đội hình.`)); }
export function restTeam(state: GameState): GameState { const actionState = spendAction(state); if (!actionState) return { ...state, transferMessage: msg('error', 'Hôm nay đã hết lượt hành động.') }; const next = syncPlayerOwnership({ ...actionState, players: actionState.players.map(p => ({ ...p, fitness: clamp(p.fitness + rand(10, 18)), morale: clamp(p.morale + rand(1, 4)) })), transferMessage: msg('success', 'Toàn đội đã nghỉ hồi phục.') }); return pushNews(pushLog(next, makeLog(next, state.club?.name ?? 'CLB', 'training', 'Nghỉ hồi phục.')), makeNews(next, 'neutral', 'Nghỉ hồi phục', 'Toàn đội được nghỉ để hồi phục thể lực và tinh thần.')); }
export function isSeasonFinished(state: GameState): boolean { return state.fixtures.length > 0 && state.fixtures.every(f => f.played); }
function calculateSeasonReward(rank: number) { if (rank === 1) return { prize: 2_000_000, reputationGain: 8, fanGain: 5_000 }; if (rank === 2) return { prize: 1_250_000, reputationGain: 5, fanGain: 2_800 }; if (rank === 3) return { prize: 850_000, reputationGain: 3, fanGain: 1_600 }; if (rank <= 5) return { prize: 450_000, reputationGain: 1, fanGain: 700 }; return { prize: 200_000, reputationGain: 0, fanGain: 150 }; }
function progressPlayerForNewSeason(player: Player): Player { const age = player.age + 1; const growth = age <= 23 && player.overall < player.potential ? rand(1, 4) : age <= 28 && player.overall < player.potential && Math.random() > 0.65 ? 1 : 0; const decline = age >= 32 ? rand(0, 2) : 0; const nextOverall = clamp(player.overall + growth - decline); const ratio = nextOverall / Math.max(player.overall, 1); return { ...player, age, overall: nextOverall, value: Math.round(nextOverall * nextOverall * 120), salary: Math.round(player.salary * (ratio > 1 ? 1.04 : 0.99)), fitness: rand(84, 100), morale: clamp(player.morale + rand(-3, 6)), form: rand(45, 85), attack: clamp(Math.round(player.attack * ratio)), defense: clamp(Math.round(player.defense * ratio)), speed: clamp(Math.round(player.speed * (age >= 31 ? 0.98 : ratio))), stamina: clamp(Math.round(player.stamina * (age >= 31 ? 0.98 : ratio))), technique: clamp(Math.round(player.technique * ratio)), passing: clamp(Math.round(player.passing * ratio)), shooting: clamp(Math.round(player.shooting * ratio)), goalkeeping: clamp(Math.round(player.goalkeeping * ratio)) }; }
export function startNextSeason(state: GameState): GameState { if (!state.club || !isSeasonFinished(state)) return state; const userRank = state.league.findIndex(team => team.name === state.club?.name) + 1; const champion = state.league[0]?.name ?? state.club.name; const reward = calculateSeasonReward(userRank || state.league.length); const players = state.players.map(progressPlayerForNewSeason).sort((a, b) => b.overall - a.overall); const club: Club = { ...state.club, budget: state.club.budget + reward.prize, reputation: clamp(state.club.reputation + reward.reputationGain, 1, 100), fans: Math.max(0, state.club.fans + reward.fanGain), lineup: buildDefaultLineup(players) }; const league = createLeague(club.name); const opponentNames = league.map(t => t.name).filter(name => name !== club.name); const next = syncPlayerOwnership({ ...state, club, players, transferMarket: mergeMarket(state.transferMarket ?? [], generateFreeAgents(8), MARKET_LIMIT), academyProspects: [], opponentClubs: generateOpponentClubs(opponentNames), opponentSquads: generateOpponentSquads(opponentNames), playerOwnership: {}, ownershipIssues: [], league, fixtures: createFixtures(club.name, league.map(t => t.name)), currentRound: 1, season: state.season + 1, day: 1, actionsRemaining: MAX_ACTIONS, maxActionsPerDay: MAX_ACTIONS, lastMatch: null, transferMessage: msg('info', 'Mùa giải mới đã bắt đầu. Lịch thi đấu và thị trường chuyển nhượng đã được bổ sung.'), lastSeasonSummary: { season: state.season, champion, userRank, prize: reward.prize, reputationGain: reward.reputationGain, fanGain: reward.fanGain } }); return pushNews(pushLog(next, makeLog(next, 'System', 'system', `Sang mùa ${state.season + 1}. ${club.name} nhận thưởng ${reward.prize.toLocaleString('vi-VN')} VND.`)), makeNews(next, 'good', `Mùa ${state.season} khép lại`, `${champion} vô địch. ${club.name} nhận thưởng ${reward.prize.toLocaleString('vi-VN')} VND và bước vào mùa mới.`)); }
