import type { GameState, MatchResult, Player, Tactic } from './types';

type Stat = { apps: number; goals: number; assists: number; yellowCards: number; redCards: number; injuries: number; ratingTotal: number; ratingCount: number };
const clamp = (v: number, min = 1, max = 99) => Math.max(min, Math.min(max, v));
const beats: Partial<Record<Tactic, Tactic>> = { pressing: 'possession', counter: 'attacking', defensive: 'pressing', possession: 'defensive', attacking: 'balanced' };
const stat = (s: GameState, p?: Player): Stat | null => { if (!p) return null; const anyState = s as unknown as { playerStats?: Record<string, Stat> }; anyState.playerStats ??= {}; anyState.playerStats[p.id] ??= { apps: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, injuries: 0, ratingTotal: 0, ratingCount: 0 }; return anyState.playerStats[p.id]; };
const rate = (s: GameState, p: Player | undefined, value: number) => { const row = stat(s, p); if (!row) return; row.ratingTotal += value; row.ratingCount += 1; };
const inc = (s: GameState, p: Player | undefined, key: keyof Omit<Stat, 'ratingTotal' | 'ratingCount'>, rating: number) => { const row = stat(s, p); if (!row) return; row[key] += 1; rate(s, p, rating); };
const top = (list: Player[], score: (p: Player) => number) => [...list].filter(p => p.position !== 'GK').sort((a, b) => score(b) - score(a));
const pick = <T,>(list: T[]) => list[Math.floor(Math.random() * Math.max(1, list.length))];
const pickScorer = (list: Player[]) => pick(top(list, p => (p.shooting || 0) + (p.attack || 0) + (p.overall || 0)).slice(0, 5)) ?? list[0];
const pickAssist = (list: Player[], scorer?: Player) => top(list, p => (p.passing || 0) + (p.technique || 0) + (p.overall || 0)).find(p => p.id !== scorer?.id) ?? list[0];
const pickKeeper = (list: Player[]) => list.find(p => p.position === 'GK') ?? list[0];
const pickDefender = (list: Player[]) => pick(top(list, p => (p.defense || 0) + (p.stamina || 0) + (p.overall || 0)).slice(0, 6)) ?? list[0];
function squadFor(s: GameState, team: string): Player[] { if (s.club && team === s.club.name) { const ids = s.club.lineup || []; return ids.map(id => s.players.find(p => p.id === id)).filter(Boolean) as Player[]; } return ((s.opponentSquads || {})[team] || []).slice(0, 11); }
function setStatus(p: Player | undefined, status: string, untilKey: string, until: number) { if (!p) return; const anyPlayer = p as unknown as Record<string, unknown>; anyPlayer.status = status; anyPlayer[untilKey] = until; }
function clearExpired(state: GameState) { const day = state.day || 1; const clear = (p: Player) => { const anyPlayer = p as unknown as Record<string, unknown>; if (Number(anyPlayer.injuryUntilDay || 0) <= day && anyPlayer.status === 'injured') anyPlayer.status = 'available'; if (Number(anyPlayer.suspendedUntilDay || 0) <= day && anyPlayer.status === 'suspended') anyPlayer.status = 'available'; }; state.players.forEach(clear); Object.values(state.opponentSquads || {}).flat().forEach(clear); }
function removeUnavailableFromLineup(state: GameState) { if (!state.club) return; const bad = new Set(state.players.filter(p => { const anyPlayer = p as unknown as Record<string, unknown>; return anyPlayer.status === 'injured' || anyPlayer.status === 'suspended'; }).map(p => p.id)); const before = state.club.lineup.length; state.club.lineup = state.club.lineup.filter(id => !bad.has(id)); if (state.club.lineup.length !== before) (state as unknown as { lineupWarning?: string }).lineupWarning = 'Một số cầu thủ chấn thương/treo giò đã bị loại khỏi đội hình.'; }
function applyTactic(state: GameState, match: MatchResult) { if (!state.club) return; const homeTactic = match.home === state.club.name ? state.club.tactic : state.opponentClubs?.[match.home]?.tactic; const awayTactic = match.away === state.club.name ? state.club.tactic : state.opponentClubs?.[match.away]?.tactic; if (!homeTactic || !awayTactic) return; const homeBeats = beats[homeTactic] === awayTactic; const awayBeats = beats[awayTactic] === homeTactic; if (!homeBeats && !awayBeats) { match.events.push({ minute: 12, type: 'info', text: 'Đấu pháp cân bằng — hai đội không tạo được lợi thế chiến thuật rõ rệt.' }); return; } const team = homeBeats ? match.home : match.away; const tactic = homeBeats ? homeTactic : awayTactic; const other = homeBeats ? awayTactic : homeTactic; match.events.push({ minute: 12, type: 'info', text: `Ưu thế chiến thuật — ${team} dùng ${tactic} khắc chế ${other}.` }); if (homeBeats && match.homeScore <= match.awayScore) match.homeScore += 1; if (awayBeats && match.awayScore <= match.homeScore) match.awayScore += 1; }
function rebuildLeague(state: GameState) { const teams = new Map(state.league.map(t => [t.name, { ...t, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, points: 0 }])); for (const f of state.fixtures || []) { if (!f.played) continue; const h = teams.get(f.home), a = teams.get(f.away); if (!h || !a) continue; h.played++; a.played++; h.goalsFor += f.homeScore; h.goalsAgainst += f.awayScore; a.goalsFor += f.awayScore; a.goalsAgainst += f.homeScore; if (f.homeScore > f.awayScore) { h.won++; h.points += 3; a.lost++; } else if (f.homeScore < f.awayScore) { a.won++; a.points += 3; h.lost++; } else { h.drawn++; a.drawn++; h.points++; a.points++; } } state.league = [...teams.values()].sort((a, b) => b.points - a.points || (b.goalsFor - b.goalsAgainst) - (a.goalsFor - a.goalsAgainst) || b.goalsFor - a.goalsFor); }
export function enrichMatchState(state: GameState): GameState { const match = state.lastMatch; if (!match || (match as unknown as { officialEnriched?: boolean }).officialEnriched) { clearExpired(state); removeUnavailableFromLineup(state); return state; } const home = squadFor(state, match.home); const away = squadFor(state, match.away); [...home, ...away].forEach(p => inc(state, p, 'apps', 6.5)); for (const e of match.events || []) { const text = e.text || ''; if (e.type === 'goal') { const team = text.startsWith(match.home) ? match.home : match.away; const squad = team === match.home ? home : away; const scorer = pickScorer(squad); const assist = pickAssist(squad, scorer); inc(state, scorer, 'goals', 8.2); inc(state, assist, 'assists', 7.4); scorer.form = clamp((scorer.form || 50) + 3); scorer.morale = clamp((scorer.morale || 50) + 2); e.text = `${team} ghi bàn — ${scorer.name} dứt điểm sau đường chuyền của ${assist.name}.`; } else if (e.type === 'save') { const keeper = pickKeeper(Math.random() > 0.5 ? home : away); rate(state, keeper, 7.1); e.text = `Cứu thua — ${keeper?.name || 'Thủ môn'} bay người cản phá cú sút nguy hiểm.`; } else if (e.type === 'injury') { const squad = Math.random() > 0.5 ? home : away; const p = pick(squad); inc(state, p, 'injuries', 5.8); if (p) { p.fitness = Math.max(30, (p.fitness || 80) - 14); setStatus(p, 'injured', 'injuryUntilDay', (state.day || 1) + 2 + Math.floor(Math.random() * 4)); e.text = `Chấn thương — ${p.name} phải nghỉ đến ngày ${(p as unknown as { injuryUntilDay: number }).injuryUntilDay}.`; } } }
 const cards = Math.random() > 0.45 ? 1 : 2; for (let i = 0; i < cards; i++) { const isHome = Math.random() > 0.5; const squad = isHome ? home : away; const team = isHome ? match.home : match.away; const p = pickDefender(squad); const red = Math.random() > 0.86; inc(state, p, red ? 'redCards' : 'yellowCards', red ? 5.2 : 5.9); if (p) { p.form = Math.max(1, (p.form || 50) - (red ? 6 : 2)); p.morale = Math.max(1, (p.morale || 50) - (red ? 8 : 2)); if (red) setStatus(p, 'suspended', 'suspendedUntilDay', (state.day || 1) + 7); match.events.push({ minute: Math.floor(25 + Math.random() * 60), type: 'card', text: `${red ? 'Thẻ đỏ' : 'Thẻ vàng'} — ${p.name} của ${team} phạm lỗi chiến thuật.` }); } }
 applyTactic(state, match); match.events = (match.events || []).sort((a, b) => a.minute - b.minute); (match as unknown as { officialEnriched: boolean }).officialEnriched = true; state.fixtures = state.fixtures.map(f => f.id === match.id ? match : f); rebuildLeague(state); clearExpired(state); removeUnavailableFromLineup(state); return state; }
