import type { Player } from './types';

export const vipPlayers: Player[] = [
  {
    id: 'vip-lionel-messi',
    name: 'Lionel Messi',
    realWorldName: 'Lionel Messi',
    isVip: true,
    avatarUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Lionel%20Messi',
    age: 37,
    position: 'FW',
    overall: 94,
    potential: 94,
    value: 22_000_000,
    salary: 420_000,
    fitness: 86,
    morale: 92,
    form: 90,
    attack: 96,
    defense: 42,
    speed: 82,
    stamina: 78,
    technique: 99,
    passing: 97,
    shooting: 96,
    goalkeeping: 10,
  },
  {
    id: 'vip-cristiano-ronaldo',
    name: 'Cristiano Ronaldo',
    realWorldName: 'Cristiano Ronaldo',
    isVip: true,
    avatarUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Cristiano%20Ronaldo',
    age: 39,
    position: 'FW',
    overall: 91,
    potential: 91,
    value: 18_000_000,
    salary: 390_000,
    fitness: 88,
    morale: 94,
    form: 87,
    attack: 95,
    defense: 45,
    speed: 84,
    stamina: 83,
    technique: 91,
    passing: 86,
    shooting: 98,
    goalkeeping: 12,
  },
  {
    id: 'vip-kylian-mbappe',
    name: 'Kylian Mbappé',
    realWorldName: 'Kylian Mbappé',
    isVip: true,
    avatarUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Kylian%20Mbappe',
    age: 25,
    position: 'FW',
    overall: 95,
    potential: 98,
    value: 35_000_000,
    salary: 520_000,
    fitness: 93,
    morale: 88,
    form: 91,
    attack: 97,
    defense: 50,
    speed: 99,
    stamina: 90,
    technique: 94,
    passing: 88,
    shooting: 95,
    goalkeeping: 9,
  },
  {
    id: 'vip-erling-haaland',
    name: 'Erling Haaland',
    realWorldName: 'Erling Haaland',
    isVip: true,
    avatarUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Erling%20Haaland',
    age: 24,
    position: 'FW',
    overall: 94,
    potential: 97,
    value: 34_000_000,
    salary: 500_000,
    fitness: 92,
    morale: 86,
    form: 90,
    attack: 96,
    defense: 52,
    speed: 90,
    stamina: 91,
    technique: 88,
    passing: 78,
    shooting: 98,
    goalkeeping: 8,
  },
  {
    id: 'vip-kevin-de-bruyne',
    name: 'Kevin De Bruyne',
    realWorldName: 'Kevin De Bruyne',
    isVip: true,
    avatarUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Kevin%20De%20Bruyne',
    age: 33,
    position: 'MF',
    overall: 93,
    potential: 93,
    value: 24_000_000,
    salary: 440_000,
    fitness: 84,
    morale: 88,
    form: 89,
    attack: 90,
    defense: 72,
    speed: 78,
    stamina: 86,
    technique: 96,
    passing: 99,
    shooting: 90,
    goalkeeping: 11,
  },
];

export function seedVipPlayers(existing: Player[]): Player[] {
  const existingIds = new Set(existing.map(player => player.id));
  return [...vipPlayers.filter(player => !existingIds.has(player.id)), ...existing];
}
